export const coilInventoryList = () => {
  return {
    responseStatusList: {
      statusList: [
        {
          statusCode: 200,
          statusType: "success",
          statusDesc: "Coil Inventory Get successfully",
        },
      ],
    },
    responseObject: {
      data: [
        {
          coilNumber: "IC/20/1234",
          grade: "30050",
          thickness: 600,
          weight: 500,
          MTC1_5T: 1500,
          MTC1_7T: 1700,
          width: 1200,
          materialType : "CRGO",
          registeredDate: "2023-10-01",
          statusType: "ready",
          qrCodeNumber: "QR1234",
          uploadedFiles: [
            {
              filename: "sample-logo.png",
              size: "4500",
              filetype: "image/png",
            },
          ],
        },
        {
          coilNumber: "IC/21/5678",
          grade: "40075",
          thickness: 700,
          weight: 600,
          MTC1_5T: 1750,
          MTC1_7T: 1950,
          width: 1300,
          registeredDate: "2023-10-02",
          statusType: "transfer",
          qrCodeNumber: "QR5678",
          uploadedFiles: [
            {
              filename: "company-logo.jpg",
              size: "5200",
              filetype: "image/jpeg",
            },
          ],
        },
        {
          coilNumber: "IC/22/9876",
          grade: "50085",
          thickness: 800,
          weight: 700,
          MTC1_5T: 1850,
          MTC1_7T: 2100,
          width: 1400,
          registeredDate: "2023-10-03",
          statusType: "ready",
          qrCodeNumber: "QR9876",
          uploadedFiles: [
            {
              filename: "brand-logo.svg",
              size: "4800",
              filetype: "image/svg+xml",
            },
          ],
        },
        {
          coilNumber: "IC/23/5432",
          grade: "25090",
          thickness: 550,
          weight: 450,
          MTC1_5T: 1200,
          MTC1_7T: 1450,
          width: 1100,
          registeredDate: "2023-10-04",
          statusType: "block",
          qrCodeNumber: "QR5432",
          uploadedFiles: [
            {
              filename: "test-logo.gif",
              size: "3000",
              filetype: "image/gif",
            },
          ],
        },
        {
          coilNumber: "IC/24/6543",
          grade: "60095",
          thickness: 900,
          weight: 800,
          MTC1_5T: 2200,
          MTC1_7T: 2400,
          width: 1500,
          registeredDate: "2023-10-05",
          statusType: "ready",
          qrCodeNumber: "QR6543",
          uploadedFiles: [
            {
              filename: "example-logo.bmp",
              size: "3500",
              filetype: "image/bmp",
            },
          ],
        },
        {
          coilNumber: "IC/25/7654",
          grade: "70085",
          thickness: 750,
          weight: 900,
          MTC1_5T: 1900,
          MTC1_7T: 2300,
          width: 1350,
          registeredDate: "2023-10-06",
          statusType: "partialUtilized",
          qrCodeNumber: "QR7654",
          uploadedFiles: [
            {
              filename: "coil-logo.png",
              size: "4000",
              filetype: "image/png",
            },
          ],
        },
        {
          coilNumber: "IC/26/8765",
          grade: "80090",
          thickness: 850,
          weight: 950,
          MTC1_5T: 2000,
          MTC1_7T: 2500,
          width: 1450,
          registeredDate: "2023-10-07",
          statusType: "ready",
          qrCodeNumber: "QR8765",
          uploadedFiles: [
            {
              filename: "coil-image.jpg",
              size: "5000",
              filetype: "image/jpeg",
            },
          ],
        },
        {
          coilNumber: "IC/27/9875",
          grade: "90095",
          thickness: 950,
          weight: 1000,
          MTC1_5T: 2100,
          MTC1_7T: 2600,
          width: 1550,
          registeredDate: "2023-10-08",
          statusType: "block",
          qrCodeNumber: "QR9875",
          uploadedFiles: [
            {
              filename: "coil-design.svg",
              size: "4800",
              filetype: "image/svg+xml",
            },
          ],
        },
        {
          coilNumber: "IC/28/6547",
          grade: "100095",
          thickness: 1050,
          weight: 1100,
          MTC1_5T: 2300,
          MTC1_7T: 2800,
          width: 1650,
          registeredDate: "2023-10-09",
          statusType: "hold",
          qrCodeNumber: "QR6547",
          uploadedFiles: [
            {
              filename: "design-logo.bmp",
              size: "3200",
              filetype: "image/bmp",
            },
          ],
        },
        {
          coilNumber: "IC/29/3245",
          grade: "110095",
          thickness: 1150,
          weight: 1200,
          MTC1_5T: 2500,
          MTC1_7T: 3000,
          width: 1750,
          registeredDate: "2023-10-10",
          statusType: "block",
          qrCodeNumber: "QR3245",
          uploadedFiles: [
            {
              filename: "coil-image2.png",
              size: "4700",
              filetype: "image/png",
            },
          ],
        },
        {
          coilNumber: "IC/30/8763",
          grade: "120095",
          thickness: 1250,
          weight: 1300,
          MTC1_5T: 2700,
          MTC1_7T: 3200,
          width: 1850,
          registeredDate: "2023-10-11",
          statusType: "ready",
          qrCodeNumber: "QR8763",
          uploadedFiles: [
            {
              filename: "coil-data.svg",
              size: "5300",
              filetype: "image/svg+xml",
            },
          ],
        },
        {
          coilNumber: "IC/31/5431",
          grade: "130095",
          thickness: 1350,
          weight: 1400,
          MTC1_5T: 2900,
          MTC1_7T: 3400,
          width: 1950,
          registeredDate: "2023-10-12",
          statusType: "block",
          qrCodeNumber: "QR5431",
          uploadedFiles: [
            {
              filename: "coil-example.jpg",
              size: "4600",
              filetype: "image/jpeg",
            },
          ],
        },
        {
          coilNumber: "IC/32/4321",
          grade: "140095",
          thickness: 1450,
          weight: 1500,
          MTC1_5T: 3100,
          MTC1_7T: 3600,
          width: 2050,
          registeredDate: "2023-10-13",
          statusType: "ready",
          qrCodeNumber: "QR4321",
          uploadedFiles: [
            {
              filename: "coil-logo.bmp",
              size: "4200",
              filetype: "image/bmp",
            },
          ],
        },
      ],
      pagination: {
        totalItems: 20,
        currentPage: 1,
        itemsPerPage: 10,
        totalPages: 2,
      },
    },
  };
};
export const coilInfo = () => {
  return {
    responseStatusList: {
      statusList: [
        {
          statusCode: 200,
          statusType: "success",
          statusDesc: "Data get successfully",
        },
      ],
    },
    responseObject: {
      data: {
        coilNumber: "IC/26/8765",
        grade: "80090",
        thickness: 0.23,
        weight: 950,
        MTC1_5T: 2000,
        MTC1_7T: 2500,
        width: 550,
        registeredDate: "2023-10-07",
        statusType: "block",
        qrCodeNumber: "QR8765",
        uploadedFiles: [
          {
            filename: "coil-design.svg",
            size: "4800",
            filetype: "image/svg+xml",
          },
        ],
      },
    },
  };
};
export const ScrapList = () => {
  return {
    responseStatusList: {
      statusList: [
        {
          statusCode: 200,
          statusType: "success",
          statusDesc: "Data get successfully",
        },
      ],
    },
    responseObject: {
      data: {
        details: [
          {
            thickness: 0.23,
            weight: 50,
            width: 380,
            typeofscrap: "start roll",
            registeredDate: "18/10/2024",
          },
          {
            thickness: 0.24,
            weight: 60,
            width: 360,
            typeofscrap: "Bhungra",
            registeredDate: "18/10/2024",
          },
          {
            thickness: 0.25,
            weight: 55,
            width: 370,
            typeofscrap: "cut piece",
            registeredDate: "18/10/2024",
          },
          {
            thickness: 0.26,
            weight: 58,
            width: 390,
            typeofscrap: "sheet metal",
            registeredDate: "13/11/2024",
          },
          {
            thickness: 0.22,
            weight: 45,
            width: 400,
            typeofscrap: "roll end",
            registeredDate: "01/01/2024",
          },
          {
            thickness: 0.27,
            weight: 65,
            width: 385,
            typeofscrap: "Bhungra",
            registeredDate: "18/10/2024",
          },
          {
            thickness: 0.28,
            weight: 70,
            width: 375,
            typeofscrap: "start roll",
            registeredDate: "18/10/2024",
          },
          {
            thickness: 0.3,
            weight: 80,
            width: 395,
            typeofscrap: "sheet metal",
            registeredDate: "18/10/2024",
          },
          {
            thickness: 0.29,
            weight: 68,
            width: 365,
            typeofscrap: "roll end",
            registeredDate: "18/10/2024",
          },
          {
            thickness: 0.31,
            weight: 75,
            width: 355,
            typeofscrap: "Bhungra",
            registeredDate: "18/10/2024",
          },
          {
            thickness: 0.32,
            weight: 72,
            width: 345,
            typeofscrap: "cut piece",
            registeredDate: "18/10/2024",
          },
          {
            thickness: 0.33,
            weight: 85,
            width: 390,
            typeofscrap: "sheet metal",
            registeredDate: "18/10/2024",
          },
          {
            thickness: 0.34,
            weight: 78,
            width: 380,
            typeofscrap: "roll end",
            registeredDate: "18/10/2024",
          },
          {
            thickness: 0.35,
            weight: 82,
            width: 370,
            typeofscrap: "start roll",
            registeredDate: "18/10/2024",
          },
          {
            thickness: 0.36,
            weight: 90,
            width: 360,
            typeofscrap: "Bhungra",
            registeredDate: "18/10/2024",
          },
        ],
      },
      pagination: {
        totalItems: 20,
        currentPage: 1,
        itemsPerPage: 10,
        totalPages: 2,
      },
    },
  };
};

export const addScrap = () => {
  return {
    responseStatusList: {
      statusList: [
        {
          statusCode: 200,
          statusType: "success",
          statusDesc: "Scrap Data Get Successfully",
        },
      ],
    },
    responseObject: {
      data: {
        scrapId: "d622c93c-3ba4-4963-b23a-eac7f953ea81",
        thickness: 2,
        weight: 233,
        materialType: "crgo",
        scrapType: "startRoll",
        scrapStatus: "none",
        actualWeight: null,
        createdAt: "2025-01-02T13:42:29.000Z",
        updatedAt: "2025-01-02T13:42:29.000Z",
      },
    },
  };
};
export const AddedCoil = () => {
  return {
    responseStatusList: {
      statusList: [
        {
          statusCode: 200,
          statusType: "success",
          statusDesc: "Data stored in Coil Inventory Successfully",
        },
      ],
    },
    responseObject: {
      data: {
        coilInventory: {
          coilNumber: "IC/95/2341",
          grade: "45545",
          thickness: 452,
          weight: 424,
          MTC1_5T: 2424,
          MTC1_7T: 24242,
          width: 4242,
          registeredDate: "2023-10-01",
          qrCodeNumber: "2424",
          uploadedFiles: [
            {
              filename: "navkar-logo.png",
              data: "",
              size: "6296",
              filetype: "image/png",
            },
          ],
        },
      },
    },
  };
};

export const ShortList = () => {
  return {
    responseStatusList: {
      statusList: [
        {
          statusCode: 200,
          statusType: "success",
          statusDesc: "Data stored in Coil Inventory Successfully",
        },
      ],
    },
    responseObject: {
      data: [
        {
          jobNumber: "JN/95/2341",
          drawingNumber: "45545",
          workOrder: "2424",
          stack: "1",
          thickness: 0.23,
          weight: 424,
          width: 242,
        },
        {
          jobNumber: "JN/96/2342",
          drawingNumber: "45546",
          workOrder: "2425",
          stack: "2",
          weight: 425,
          width: 4243,
        },
        {
          jobNumber: "JN/97/2343",
          drawingNumber: "45547",
          workOrder: "2426",
          stack: "3",
          weight: 426,
          width: 4244,
        },
        {
          jobNumber: "JN/98/2344",
          drawingNumber: "45548",
          workOrder: "2427",
          stack: "4",
          weight: 427,
          width: 4245,
        },
        {
          jobNumber: "JN/99/2345",
          drawingNumber: "45549",
          workOrder: "2428",
          stack: "5",
          weight: 428,
          width: 4246,
        },
        {
          jobNumber: "JN/00/2346",
          drawingNumber: "45550",
          workOrder: "2429",
          stack: "6",
          weight: 429,
          width: 4247,
        },
        {
          jobNumber: "JN/01/2347",
          drawingNumber: "45551",
          workOrder: "2430",
          stack: "7",
          weight: 430,
          width: 4248,
        },
        {
          jobNumber: "JN/02/2348",
          drawingNumber: "45552",
          workOrder: "2431",
          stack: "8",
          weight: 431,
          width: 4249,
        },
        {
          jobNumber: "JN/03/2349",
          drawingNumber: "45553",
          workOrder: "2432",
          stack: "9",
          weight: 432,
          width: 4250,
        },
        {
          jobNumber: "JN/04/2350",
          drawingNumber: "45554",
          workOrder: "2433",
          stack: "10",
          weight: 433,
          width: 4251,
        },
        {
          jobNumber: "JN/05/2351",
          drawingNumber: "45555",
          workOrder: "2434",
          stack: "11",
          weight: 434,
          width: 4252,
        },
        {
          jobNumber: "JN/06/2352",
          drawingNumber: "45556",
          workOrder: "2435",
          stack: "12",
          weight: 435,
          width: 4253,
        },
        {
          jobNumber: "JN/07/2353",
          drawingNumber: "45557",
          workOrder: "2436",
          stack: "13",
          weight: 436,
          width: 4254,
        },
        {
          jobNumber: "JN/08/2354",
          drawingNumber: "45558",
          workOrder: "2437",
          stack: "14",
          weight: 437,
          width: 4255,
        },
        {
          jobNumber: "JN/09/2355",
          drawingNumber: "45559",
          workOrder: "2438",
          stack: "15",
          weight: 438,
          width: 4256,
        },
      ],
      pagination: {
        totalItems: 20,
        currentPage: 1,
        itemsPerPage: 10,
        totalPages: 2,
      },
    },
  };
};
export const RollInventoryList = () => {
  return {
    responseStatusList: {
      statusList: [
        {
          statusCode: 200,
          statusType: "success",
          statusDesc: "Roll Inventory Data Get Successfully",
        },
      ],
    },
    responseObject: {
      data: [
        {
          rollid: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
          coilNumber: "coil123",
          rollNumber: "Extra2-12345678",
          jobNumber: null,
          drawingNumber: null,
          workOrder: null,
          stack: 60,
          width: 4000,
          thickness: 400,
          length: 500,
          weight: 2100,
          splittingId: null,
          rollstatus: "extra",
          subStatus: {},
          createdAt: "2025-01-06T17:39:30.000Z",
          updatedAt: "2025-01-09T04:14:37.106Z",
          createdBy: null,
          updatedBy: "Slitting Supervisor",
          endDate: null,
          slittingProgramId: "d1e2f3g4-h5i6-7890-jklm-nopqrstuvwxyz",
          grade: 220,
          MTC1_7T: 25000,
          materialType: "CRNO",
        },
        {
          rollid: "a1b2c3d4-e5f6-7890-abcd-ef1234567891",
          rollNumber: "Extra2-23456789",
          jobNumber: "job123",
          drawingNumber: "drawing123",
          workOrder: "workOrder123",
          stack: 70,
          width: 4200,
          thickness: 410,
          length: 500,
          weight: 2200,
          splittingId: null,
          rollstatus: "hold",
          subStatus: {},
          createdAt: "2025-01-06T17:39:30.000Z",
          updatedAt: "2025-01-09T04:14:37.106Z",
          createdBy: null,
          updatedBy: "Slitting Supervisor",
          endDate: null,
          slittingProgramId: "d1e2f3g4-h5i6-7890-jklm-nopqrstuvwxyz",
          grade: 225,
          MTC1_7T: 25500,
          materialType: "CRGO",
        },
        {
          rollid: "a1b2c3d4-e5f6-7890-abcd-ef1234567892",
          rollNumber: "Extra2-34567890",
          jobNumber: "job456",
          drawingNumber: "drawing456",
          workOrder: "workOrder456",
          stack: 80,
          width: 4400,
          thickness: 420,
          length: 500,
          weight: 2300,
          splittingId: null,
          rollstatus: "extra",
          subStatus: {},
          createdAt: "2025-01-06T17:39:30.000Z",
          updatedAt: "2025-01-09T04:14:37.106Z",
          createdBy: null,
          updatedBy: "Slitting Supervisor",
          endDate: null,
          slittingProgramId: "d1e2f3g4-h5i6-7890-jklm-nopqrstuvwxyz",
          grade: 230,
          MTC1_7T: 26000,
        },
        {
          rollid: "a1b2c3d4-e5f6-7890-abcd-ef1234567893",
          rollNumber: "Extra2-45678901",
          jobNumber: "job789",
          drawingNumber: "drawing789",
          workOrder: "workOrder789",
          stack: 90,
          width: 4600,
          thickness: 430,
          length: 500,
          weight: 2400,
          splittingId: null,
          rollstatus: "hold",
          subStatus: {},
          createdAt: "2025-01-06T17:39:30.000Z",
          updatedAt: "2025-01-09T04:14:37.106Z",
          createdBy: null,
          updatedBy: "Slitting Supervisor",
          endDate: null,
          slittingProgramId: "d1e2f3g4-h5i6-7890-jklm-nopqrstuvwxyz",
          grade: 235,
          MTC1_7T: 26500,
        },
        {
          rollid: "a1b2c3d4-e5f6-7890-abcd-ef1234567894",
          rollNumber: "Extra2-56789012",
          jobNumber: "job101",
          drawingNumber: "drawing101",
          workOrder: "workOrder101",
          stack: 100,
          width: 4800,
          thickness: 440,
          length: 1000,
          weight: 2500,
          splittingId: null,
          rollstatus: "extra",
          subStatus: {},
          createdAt: "2025-01-06T17:39:30.000Z",
          updatedAt: "2025-01-09T04:14:37.106Z",
          createdBy: null,
          updatedBy: "Slitting Supervisor",
          endDate: null,
          slittingProgramId: "d1e2f3g4-h5i6-7890-jklm-nopqrstuvwxyz",
          grade: 240,
          MTC1_7T: 27000,
        },
        {
          rollid: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
          rollNumber: "Extra2-12345678",
          jobNumber: null,
          drawingNumber: null,
          workOrder: null,
          stack: 60,
          width: 4000,
          thickness: 400,
          length: 500,
          weight: 2100,
          splittingId: null,
          rollstatus: "extra",
          subStatus: {},
          createdAt: "2025-01-06T17:39:30.000Z",
          updatedAt: "2025-01-09T04:14:37.106Z",
          createdBy: null,
          updatedBy: "Slitting Supervisor",
          endDate: null,
          slittingProgramId: "d1e2f3g4-h5i6-7890-jklm-nopqrstuvwxyz",
          grade: 220,
          MTC1_7T: 25000,
        },
        {
          rollid: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
          rollNumber: "Extra2-12345678",
          jobNumber: null,
          drawingNumber: null,
          workOrder: null,
          stack: 60,
          width: 4000,
          thickness: 400,
          length: 500,
          weight: 2100,
          splittingId: null,
          rollstatus: "extra",
          subStatus: {},
          createdAt: "2025-01-06T17:39:30.000Z",
          updatedAt: "2025-01-09T04:14:37.106Z",
          createdBy: null,
          updatedBy: "Slitting Supervisor",
          endDate: null,
          slittingProgramId: "d1e2f3g4-h5i6-7890-jklm-nopqrstuvwxyz",
          grade: 220,
          MTC1_7T: 25000,
        },
        {
          rollid: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
          rollNumber: "Extra2-12345678",
          jobNumber: null,
          drawingNumber: null,
          workOrder: null,
          stack: 60,
          width: 4000,
          thickness: 400,
          length: 500,
          weight: 2100,
          splittingId: null,
          rollstatus: "extra",
          subStatus: {},
          createdAt: "2025-01-06T17:39:30.000Z",
          updatedAt: "2025-01-09T04:14:37.106Z",
          createdBy: null,
          updatedBy: "Slitting Supervisor",
          endDate: null,
          slittingProgramId: "d1e2f3g4-h5i6-7890-jklm-nopqrstuvwxyz",
          grade: 220,
          MTC1_7T: 25000,
        },
        {
          rollid: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
          rollNumber: "Extra2-12345678",
          jobNumber: null,
          drawingNumber: null,
          workOrder: null,
          stack: 60,
          width: 4000,
          thickness: 400,
          length: 500,
          weight: 2100,
          splittingId: null,
          rollstatus: "extra",
          subStatus: {},
          createdAt: "2025-01-06T17:39:30.000Z",
          updatedAt: "2025-01-09T04:14:37.106Z",
          createdBy: null,
          updatedBy: "Slitting Supervisor",
          endDate: null,
          slittingProgramId: "d1e2f3g4-h5i6-7890-jklm-nopqrstuvwxyz",
          grade: 220,
          MTC1_7T: 25000,
        },
        {
          rollid: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
          rollNumber: "Extra2-12345678",
          jobNumber: null,
          drawingNumber: null,
          workOrder: null,
          stack: 60,
          width: 4000,
          thickness: 400,
          length: 500,
          weight: 2100,
          splittingId: null,
          rollstatus: "extra",
          subStatus: {},
          createdAt: "2025-01-06T17:39:30.000Z",
          updatedAt: "2025-01-09T04:14:37.106Z",
          createdBy: null,
          updatedBy: "Slitting Supervisor",
          endDate: null,
          slittingProgramId: "d1e2f3g4-h5i6-7890-jklm-nopqrstuvwxyz",
          grade: 220,
          MTC1_7T: 25000,
        },
        {
          rollid: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
          rollNumber: "Extra2-12345678",
          jobNumber: null,
          drawingNumber: null,
          workOrder: null,
          stack: 60,
          width: 4000,
          thickness: 400,
          length: 500,
          weight: 2100,
          splittingId: null,
          rollstatus: "extra",
          subStatus: {},
          createdAt: "2025-01-06T17:39:30.000Z",
          updatedAt: "2025-01-09T04:14:37.106Z",
          createdBy: null,
          updatedBy: "Slitting Supervisor",
          endDate: null,
          slittingProgramId: "d1e2f3g4-h5i6-7890-jklm-nopqrstuvwxyz",
          grade: 220,
          MTC1_7T: 25000,
        },
        {
          rollid: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
          rollNumber: "Extra2-12345678",
          jobNumber: null,
          drawingNumber: null,
          workOrder: null,
          stack: 60,
          width: 4000,
          thickness: 400,
          length: 500,
          weight: 2100,
          splittingId: null,
          rollstatus: "extra",
          subStatus: {},
          createdAt: "2025-01-06T17:39:30.000Z",
          updatedAt: "2025-01-09T04:14:37.106Z",
          createdBy: null,
          updatedBy: "Slitting Supervisor",
          endDate: null,
          slittingProgramId: "d1e2f3g4-h5i6-7890-jklm-nopqrstuvwxyz",
          grade: 220,
          MTC1_7T: 25000,
        },
        {
          rollid: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
          rollNumber: "Extra2-12345678",
          jobNumber: null,
          drawingNumber: null,
          workOrder: null,
          stack: 60,
          width: 4000,
          thickness: 400,
          length: 500,
          weight: 2100,
          splittingId: null,
          rollstatus: "extra",
          subStatus: {},
          createdAt: "2025-01-06T17:39:30.000Z",
          updatedAt: "2025-01-09T04:14:37.106Z",
          createdBy: null,
          updatedBy: "Slitting Supervisor",
          endDate: null,
          slittingProgramId: "d1e2f3g4-h5i6-7890-jklm-nopqrstuvwxyz",
          grade: 220,
          MTC1_7T: 25000,
        },
        {
          rollid: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
          rollNumber: "Extra2-12345678",
          jobNumber: null,
          drawingNumber: null,
          workOrder: null,
          stack: 60,
          width: 4000,
          thickness: 400,
          length: 500,
          weight: 2100,
          splittingId: null,
          rollstatus: "extra",
          subStatus: {},
          createdAt: "2025-01-06T17:39:30.000Z",
          updatedAt: "2025-01-09T04:14:37.106Z",
          createdBy: null,
          updatedBy: "Slitting Supervisor",
          endDate: null,
          slittingProgramId: "d1e2f3g4-h5i6-7890-jklm-nopqrstuvwxyz",
          grade: 220,
          MTC1_7T: 25000,
        },
      ],
      pagination: {
        totalItems: 20,
        currentPage: 1,
        itemsPerPage: 5,
        totalPages: 4,
      },
    },
  };
};

export const JobOrderList = () => {
  return {
    responseStatusList: {
      statusList: [
        {
          statusCode: 200,
          statusType: "success",
          statusDesc: "jobAttributess Submit successfully",
        },
      ],
    },
    responseObject: {
      data: [
        {
          jobNumber: 111168,
          sets: 2,
          drawingNumber: 10436,
          customerjobNumber: "CN_10436",
          workOrder: 10436,
          PONo: "PN_10436",
          customerName: "TDR",
          isPacked: true,
          jobAttributes: [
            {
              width: 255,
              trimmingWeight: 2.12,
              processWeight: 540,
              programStatus: "slitting",
            },
            {
              width: 300,
              trimmingWeight: 3.01,
              processWeight: 600,
              programStatus: "cutting",
            },
          ],
        },
        {
          jobNumber: 111169,
          sets: 3,
          drawingNumber: 10437,
          customerjobNumber: "CN_10437",
          workOrder: 10437,
          PONo: "PN_10437",
          customerName: "XYZ",

          jobAttributes: [
            {
              width: 260,
              trimmingWeight: 2.25,
              processWeight: 560,
            },
            {
              width: 310,
              trimmingWeight: 3.1,
              processWeight: 610,
            },
          ],
        },
        {
          jobNumber: 111170,
          sets: 1,
          drawingNumber: 10438,
          customerjobNumber: "CN_10438",
          workOrder: 10438,
          PONo: "PN_10438",
          customerName: "ABC",
          jobAttributes: [
            {
              width: 265,
              trimmingWeight: 2.3,
              processWeight: 570,
            },
            {
              width: 315,
              trimmingWeight: 3.15,
              processWeight: 620,
            },
          ],
        },
        {
          jobNumber: 111171,
          sets: 4,
          drawingNumber: 10439,
          customerjobNumber: "CN_10439",
          workOrder: 10439,
          PONo: "PN_10439",
          customerName: "TDR",
          jobAttributes: [
            {
              width: 270,
              trimmingWeight: 2.5,
              processWeight: 580,
            },
            {
              width: 320,
              trimmingWeight: 3.25,
              processWeight: 630,
            },
          ],
        },
        {
          jobNumber: 111172,
          sets: 2,
          drawingNumber: 10440,
          customerjobNumber: "CN_10440",
          workOrder: 10440,
          PONo: "PN_10440",
          customerName: "XYZ",
          jobAttributes: [
            {
              width: 275,
              trimmingWeight: 2.55,
              processWeight: 590,
            },
            {
              width: 325,
              trimmingWeight: 3.3,
              processWeight: 640,
            },
          ],
        },
        {
          jobNumber: 111173,
          sets: 5,
          drawingNumber: 10441,
          customerjobNumber: "CN_10441",
          workOrder: 10441,
          PONo: "PN_10441",
          customerName: "ABC",
          jobAttributes: [
            {
              width: 280,
              trimmingWeight: 2.6,
              processWeight: 600,
            },
            {
              width: 330,
              trimmingWeight: 3.4,
              processWeight: 650,
            },
          ],
        },
        {
          jobNumber: 111174,
          sets: 1,
          drawingNumber: 10442,
          customerjobNumber: "CN_10442",
          workOrder: 10442,
          PONo: "PN_10442",
          customerName: "TDR",
          jobAttributes: [
            {
              width: 285,
              trimmingWeight: 2.7,
              processWeight: 610,
            },
            {
              width: 335,
              trimmingWeight: 3.5,
              processWeight: 660,
            },
          ],
        },
        {
          jobNumber: 111175,
          sets: 3,
          drawingNumber: 10443,
          customerjobNumber: "CN_10443",
          workOrder: 10443,
          PONo: "PN_10443",
          customerName: "XYZ",
          jobAttributes: [
            {
              width: 290,
              trimmingWeight: 2.8,
              processWeight: 620,
            },
            {
              width: 340,
              trimmingWeight: 3.6,
              processWeight: 670,
            },
          ],
        },
        {
          jobNumber: 111176,
          sets: 2,
          drawingNumber: 10444,
          customerjobNumber: "CN_10444",
          workOrder: 10444,
          PONo: "PN_10444",
          customerName: "ABC",
          jobAttributes: [
            {
              width: 295,
              trimmingWeight: 2.9,
              processWeight: 630,
            },
            {
              width: 345,
              trimmingWeight: 3.7,
              processWeight: 680,
            },
          ],
        },
        {
          jobNumber: 111177,
          sets: 4,
          drawingNumber: 10445,
          customerjobNumber: "CN_10445",
          workOrder: 10445,
          PONo: "PN_10445",
          customerName: "TDR",
          jobAttributes: [
            {
              width: 300,
              trimmingWeight: 3.0,
              processWeight: 640,
            },
            {
              width: 350,
              trimmingWeight: 3.8,
              processWeight: 690,
            },
          ],
        },
      ],
      pagination: {
        totalItems: 20,
        currentPage: 1,
        itemsPerPage: 10,
        totalPages: 2,
      },
    },
  };
};

export const SlittingList = () => {
  return {
    responseStatusList: {
      statusList: [
        {
          statusCode: 200,
          statusType: "success",
          statusDesc: "Data get successfully",
        },
      ],
    },
    responseObject: {
      data: [
        {
          coilNumber: "IC/31/978",
          width: 2.3,
          thickness: 0.27,
          weight: 1500,
          slittingData: [
            {
              jobNumber: "11123",
              drawingNumber: "MH123124",
              workOrder: "1121",
              stack: 50,
              length: 32,
              width: 380,
              weight: 250,
              expected: 300,
              thickness: 0.27,
              cutInMeters: null,
              status: "Hold",
            },
            {
              jobNumber: "11123",
              drawingNumber: "MH123124",
              workOrder: "1121",
              stack: 50,
              length: 32,
              width: 380,
              weight: 250,
              expected: 300,
              thickness: 0.27,
              cutInMeters: null,
              status: "Ready",
            },
            {
              jobNumber: "11123",
              drawingNumber: "MH123124",
              workOrder: "1121",
              stack: 50,
              length: 32,
              width: 380,
              weight: 250,
              expected: 300,
              thickness: 0.27,
              cutInMeters: null,
              status: "Ready",
            },
          ],
        },
      ],
      pagination: {
        totalItems: 20,
        currentPage: 1,
        itemsPerPage: 10,
        totalPages: 2,
      },
    },
  };
};

export const plannedSlitting = () => {
  return {
    responseStatusList: {
      statusList: [
        {
          statusCode: 200,
          statusType: "success",
          statusDesc: "jobAttributess Submit successfully",
        },
      ],
    },
    responseObject: {
      data: [
        {
          coil_roll_no: "IC/45/123",
          details: [
            {
              thickness: 0.22,
              weight: 800,
              width: 350,
              drawingNumber: "MEHI-9001",
              workOrder: 2001,
              jobNumber: 12001,
            },
            {
              thickness: 0.23,
              weight: 780,
              width: 360,
              drawingNumber: "MEHI-9002",
              workOrder: 2002,
              jobNumber: 12002,
            },
            {
              thickness: 0.24,
              weight: 760,
              width: 370,
              drawingNumber: "MEHI-9003",
              workOrder: 2003,
              jobNumber: 12003,
            },
            {
              thickness: 0.25,
              weight: 740,
              width: 380,
              drawingNumber: "MEHI-9004",
              workOrder: 2004,
              jobNumber: 12004,
            },
          ],
        },
        {
          coil_roll_no: "Ro/5687",
          details: [
            {
              thickness: 0.26,
              weight: 450,
              width: 330,
              drawingNumber: "MEHI-9011",
              workOrder: 2011,
              jobNumber: 12011,
            },
            {
              thickness: 0.27,
              weight: 440,
              width: 340,
              drawingNumber: "MEHI-9012",
              workOrder: 2012,
              jobNumber: 12012,
            },
          ],
        },
        {
          coil_roll_no: "IC/76/555",
          details: [
            {
              thickness: 0.28,
              weight: 900,
              width: 400,
              drawingNumber: "MEHI-9021",
              workOrder: 2021,
              jobNumber: 12021,
            },
            {
              thickness: 0.29,
              weight: 880,
              width: 410,
              drawingNumber: "MEHI-9022",
              workOrder: 2022,
              jobNumber: 12022,
            },
            {
              thickness: 0.3,
              weight: 860,
              width: 420,
              drawingNumber: "MEHI-9023",
              workOrder: 2023,
              jobNumber: 12023,
            },
          ],
        },
        {
          coil_roll_no: "Ro/3321",
          details: [
            {
              thickness: 0.31,
              weight: 500,
              width: 350,
              drawingNumber: "MEHI-9031",
              workOrder: 2031,
              jobNumber: 12031,
            },
            {
              thickness: 0.32,
              weight: 480,
              width: 360,
              drawingNumber: "MEHI-9032",
              workOrder: 2032,
              jobNumber: 12032,
            },
          ],
        },
        {
          coil_roll_no: "IC/88/234",
          details: [
            {
              thickness: 0.33,
              weight: 720,
              width: 390,
              drawingNumber: "MEHI-9041",
              workOrder: 2041,
              jobNumber: 12041,
            },
            {
              thickness: 0.34,
              weight: 700,
              width: 400,
              drawingNumber: "MEHI-9042",
              workOrder: 2042,
              jobNumber: 12042,
            },
            {
              thickness: 0.35,
              weight: 680,
              width: 410,
              drawingNumber: "MEHI-9043",
              workOrder: 2043,
              jobNumber: 12043,
            },
          ],
        },
      ],
      pagination: {
        totalItems: 20,
        currentPage: 1,
        itemsPerPage: 10,
        totalPages: 2,
      },
    },
  };
};

export const JobNumberList = () => {
  return {
    responseStatusList: {
      statusList: [
        {
          statusCode: 200,
          statusType: "success",
          statusDesc: "Getting Job Detail List successfully",
        },
      ],
    },
    responseObject: {
      data: [
        {
          jobNumber: "111169",
          sets: 1,
          drawingNumber: "10432",
          customerjobNumber: "CN_1046",
          workOrder: "1245236",
          PONo: "PN_1035",
          customerName: "TDN",
          jobAttributes: [
            {
              width: 25,
              occupied: false,
              processWeight: 500,
              trimmingWeight: 2.8,
            },
            {
              width: 23,
              occupied: true,
              processWeight: 500,
              trimmingWeight: 2.8,
            },
          ],
          createdAt: "2024-12-31T11:10:15.000Z",
          updatedAt: "2024-12-31T11:10:15.000Z",
          endDate: null,
        },
        {
          jobNumber: "111168",
          sets: 1,
          drawingNumber: "104002",
          customerjobNumber: "CN_1046",
          workOrder: "1034",
          PONo: "PN_1035",
          customerName: "TDN",
          jobAttributes: [
            {
              width: 26,
              occupied: false,
              processWeight: 500,
              trimmingWeight: 2.8,
              programStatus: "Cutting",
            },
            {
              width: 23,
              occupied: false,
              processWeight: 500,
              trimmingWeight: 2.8,
              programStatus: "Slitting",
            },
          ],
          createdAt: "2024-12-31T10:55:05.000Z",
          updatedAt: "2024-12-31T10:55:05.000Z",
          endDate: null,
        },
        {
          jobNumber: "111170",
          sets: 1,
          drawingNumber: "104002",
          customerjobNumber: "CN_1046",
          workOrder: "1034",
          PONo: "PN_1035",
          customerName: "TDN",
          jobAttributes: [
            {
              width: 46,
              occupied: false,
              processWeight: 500,
              trimmingWeight: 2.8,
            },
            {
              width: 65,
              occupied: false,
              processWeight: 500,
              trimmingWeight: 2.8,
            },
            {
              width: 23,
              occupied: false,
              processWeight: 500,
              trimmingWeight: 2.8,
            },
            {
              width: 51,
              occupied: false,
              processWeight: 500,
              trimmingWeight: 2.8,
            },
          ],
          createdAt: "2024-12-31T10:55:05.000Z",
          updatedAt: "2024-12-31T10:55:05.000Z",
          endDate: null,
        },
      ],
      pagination: null,
    },
  };
};

export const rollsReadyCutting = () => {
  return {
    responseStatusList: {
      statusList: [
        {
          statusCode: 200,
          statusType: "success",
          statusDesc: "Rolls Ready Cutting Get successfully",
        },
      ],
    },
    responseObject: {
      data: [
        {
          rollNumber: "IR/001a",
          jobNumber: "12121",
          workOrder: "1011",
          drawingNumber: "DR1001",
          width: 450,
          weight: 250,
          thickness: 2.5,

          stack: 60,
          status: "Pending",
        },
        {
          rollNumber: "IR/002b",
          jobNumber: "13131",
          workOrder: "2022",
          drawingNumber: "DR2002",
          width: 400,
          weight: 300,
          thickness: 2.8,

          stack: 55,
          status: "Completed",
        },
        {
          rollNumber: "IR/003c",
          jobNumber: "14141",
          workOrder: "3033",
          drawingNumber: "DR3003",
          width: 380,
          weight: 280,
          thickness: 3.0,

          stack: 50,
          status: "In Progress",
        },
        {
          rollNumber: "IR/004d",
          jobNumber: "15151",
          workOrder: "4044",
          drawingNumber: "DR4004",
          width: 420,
          weight: 220,
          thickness: 2.4,

          stack: 45,
          status: "Pending",
        },
        {
          rollNumber: "IR/005e",
          jobNumber: "16161",
          workOrder: "5055",
          drawingNumber: "DR5005",
          width: 460,
          weight: 310,
          thickness: 2.9,

          stack: 65,
          status: "Completed",
        },
      ],
      pagination: {
        totalItems: 20,
        currentPage: 1,
        itemsPerPage: 10,
        totalPages: 2,
      },
    },
  };
};

export const updateRollsReadyCutting = () => {
  return {
    responseStatusList: {
      statusList: [
        {
          statusCode: 200,
          statusType: "success",
          statusDesc: "Data of Ready rolls for cutting get  successfully",
        },
      ],
    },
    responseObject: {
      data: {
        rollNumber: "IR/546/663",
        status: null,
        actualWeight: 654,
        scrapType: "startRoll",
        productionLine: 1,
        balancedRoll: {
          width: 200,
          stack: 50,
          weight: 230,
        },
        qrCodeNumber: "a65asd+asafa65",
      },
    },
  };
};

export const slittingOperatorFinishResponse = () => {
  return {
    responseStatusList: {
      statusList: [
        {
          statusCode: 200,
          statusType: "success",
          statusDesc: "Data updated Successfully by Slitting Operator",
        },
      ],
    },
    responseObject: {
      data: [
        {
          slittingProgramId: "b1ef60fd-311f-476a-9956-ec7425c18de8",
          slittingProgramStatus: "none",
          coil_rollNumber: "IC/23/aasd34",
          rollNumber: null,
          width: 1200,
          thickness: 0.23,
          weight: 2000,
          programTrim: 6,
          rollsData: [
            {
              stack: 50,
              width: 240,
              length: 36,
              rollId: "f26a5cc2-b9a5-4935-96d2-87acd148e317",
              weight: 2.3,
              occupied: true,
              jobNumber: "3a1sd63a5s",
              subStatus: "Bulging",
              thickness: 15,
              workOrder: "1121",
              cutInMeter: 1,
              rollStatus: "hold",
              drawingNumber: "asiloas",
              splittingRollId: null,
              qrCodeNumber: "a65asd+asafa65",
              rollTrim: 2.5,
            },
            {
              stack: 50,
              width: 240,
              length: 36,
              rollId: "f26a5cc2-b9a5-4935-96d2-87acd148e317",
              weight: 2.3,
              occupied: true,
              jobNumber: "3a1sd63a5s",
              subStatus: "Bulging",
              thickness: 15,
              workOrder: "1121",
              cutInMeter: 1,
              rollStatus: "ready",
              drawingNumber: "asiloas",
              splittingRollId: null,
              qrCodeNumber: "a65asd+asafa65",
              rollTrim: 3.5,
            },
            {
              stack: 50,
              width: 120,
              length: 36,
              rollId: "f26a5cc2-b9a5-4935-96d2-87acd148e317",
              weight: 2.3,
              occupied: true,
              jobNumber: "3a1sd63a5s",
              subStatus: "Bulging",
              thickness: 15,
              workOrder: "1121",
              cutInMeter: 1,
              rollStatus: "hold",
              drawingNumber: "asiloas",
              splittingRollId: null,
              qrCodeNumber: "a65asd+asafa65",
              rollTrim: 6,
            },
            {
              stack: 50,
              width: 160,
              length: 36,
              rollId: "f26a5cc2-b9a5-4935-96d2-87acd148e317",
              weight: 2.3,
              occupied: true,
              jobNumber: "3a1sd63a5s",
              subStatus: "Bulging",
              thickness: 15,
              workOrder: "1121",
              cutInMeter: 1,
              rollStatus: "ready",
              drawingNumber: "asiloas",
              splittingRollId: "asdasdasd",
              qrCodeNumber: "a65asd+asafa65",
              rollTrim: 3.2,
            },
            {
              stack: 50,
              width: 160,
              length: 36,
              rollId: "f26a5cc2-b9a5-4935-96d2-87acd148e317",
              weight: 2.3,
              occupied: true,
              jobNumber: "3a1sd63a5s",
              subStatus: "Bulging",
              thickness: 15,
              workOrder: "1121",
              cutInMeter: 1,
              rollStatus: "hold",
              drawingNumber: "asiloas",
              splittingRollId: "asdasdasd",
              qrCodeNumber: "a65asd+asafa65",
              rollTrim: 2.8,
            },
          ],
          documentId: [],
          extraRoll: {
            stack: 50,
            width: 1098,
            weight: 15.4,
            thickness: 2,
          },
          statusDescription: null,
          isSplitted: null,
          productionLine: null,
          actualWeight: null,
          scrapType: null,
          createdAt: "2025-01-01T17:49:58.000Z",
          updatedAt: "2025-01-01T17:56:14.000Z",
          createdBy: "Slitting Supervisor",
          updatedBy: "Slitting Operator",
          endDate: null,
        },
      ],
      pagination: {
        current_page: 1,
        itemsPerPage: 30,
        total_Items: 5,
        total_pages: 1,
      },
    },
  };
};
export const packing = () => {
  return {
    responseStatusList: {
      statusList: [
        {
          statusCode: 200,
          statusType: "success",
          statusDesc: "Packing Data Get Successfully",
        },
      ],
    },
    responseObject: {
      data: [
        {
          jobNumber: "IC/567/8901_01_01",
          drawingNumber: "123456",
          workOrder: "5678",
          jobAttributes: [
            {
              width: 400,
              weight: 800,
              stack: null,
              packedWeight: null,
              scrap: null,
              excessWeight: null,
            },
            {
              width: 420,
              weight: 850,
              stack: null,
              packedWeight: null,
              scrap: null,
              excessWeight: null,
            },
            {
              width: 410,
              weight: 820,
              stack: null,
              packedWeight: null,
              scrap: null,
              excessWeight: null,
            },
            {
              width: 430,
              weight: 870,
              stack: null,
              packedWeight: null,
              scrap: null,
              excessWeight: null,
            },
          ],
        },
        {
          jobNumber: "IC/567/8901_01_02",
          drawingNumber: "654321",
          workOrder: "6789",
          jobAttributes: [
            {
              width: 390,
              weight: 750,
              stack: null,
              packedWeight: null,
              scrap: null,
              excessWeight: null,
            },
            {
              width: 410,
              weight: 780,
              stack: null,
              packedWeight: null,
              scrap: null,
              excessWeight: null,
            },
            {
              width: 400,
              weight: 760,
              stack: null,
              packedWeight: null,
              scrap: null,
              excessWeight: null,
            },
            {
              width: 420,
              weight: 790,
              stack: null,
              packedWeight: null,
              scrap: null,
              excessWeight: null,
            },
          ],
        },
        {
          jobNumber: "IC/567/8901_01_03",
          drawingNumber: "789012",
          workOrder: "7890",
          jobAttributes: [
            {
              width: 380,
              weight: 720,
              stack: null,
              packedWeight: null,
              scrap: null,
              excessWeight: null,
            },
            {
              width: 390,
              weight: 740,
              stack: null,
              packedWeight: null,
              scrap: null,
              excessWeight: null,
            },
            {
              width: 400,
              weight: 750,
              stack: null,
              packedWeight: null,
              scrap: null,
              excessWeight: null,
            },
            {
              width: 410,
              weight: 760,
              stack: null,
              packedWeight: null,
              scrap: null,
              excessWeight: null,
            },
          ],
        },
        {
          jobNumber: "IC/567/8901_01_04",
          drawingNumber: "890123",
          workOrder: "8901",
          jobAttributes: [
            {
              width: 370,
              weight: 700,
              stack: null,
              packedWeight: null,
              scrap: null,
              excessWeight: null,
            },
            {
              width: 380,
              weight: 710,
              stack: null,
              packedWeight: null,
              scrap: null,
              excessWeight: null,
            },
            {
              width: 390,
              weight: 720,
              stack: null,
              packedWeight: null,
              scrap: null,
              excessWeight: null,
            },
            {
              width: 400,
              weight: 730,
              stack: null,
              packedWeight: null,
              scrap: null,
              excessWeight: null,
            },
          ],
        },
        {
          jobNumber: "IC/567/8901_01_05",
          drawingNumber: "901234",
          workOrder: "9012",
          jobAttributes: [
            {
              width: 360,
              weight: 680,
              stack: null,
              packedWeight: null,
              scrap: null,
              excessWeight: null,
            },
            {
              width: 370,
              weight: 690,
              stack: null,
              packedWeight: null,
              scrap: null,
              excessWeight: null,
            },
            {
              width: 380,
              weight: 700,
              stack: null,
              packedWeight: null,
              scrap: null,
              excessWeight: null,
            },
            {
              width: 390,
              weight: 710,
              stack: null,
              packedWeight: null,
              scrap: null,
              excessWeight: null,
            },
          ],
        },
        {
          jobNumber: "IC/567/8901_01_01",
          drawingNumber: "123456",
          workOrder: "5678",
          jobAttributes: [
            {
              width: 400,
              weight: 800,
              stack: null,
              packedWeight: null,
              scrap: null,
              excessWeight: null,
            },
            {
              width: 420,
              weight: 850,
              stack: null,
              packedWeight: null,
              scrap: null,
              excessWeight: null,
            },
            {
              width: 410,
              weight: 820,
              stack: null,
              packedWeight: null,
              scrap: null,
              excessWeight: null,
            },
            {
              width: 430,
              weight: 870,
              stack: null,
              packedWeight: null,
              scrap: null,
              excessWeight: null,
            },
          ],
        },
        {
          jobNumber: "IC/567/8901_01_02",
          drawingNumber: "654321",
          workOrder: "6789",
          jobAttributes: [
            {
              width: 390,
              weight: 750,
              stack: null,
              packedWeight: null,
              scrap: null,
              excessWeight: null,
            },
            {
              width: 410,
              weight: 780,
              stack: null,
              packedWeight: null,
              scrap: null,
              excessWeight: null,
            },
            {
              width: 400,
              weight: 760,
              stack: null,
              packedWeight: null,
              scrap: null,
              excessWeight: null,
            },
            {
              width: 420,
              weight: 790,
              stack: null,
              packedWeight: null,
              scrap: null,
              excessWeight: null,
            },
          ],
        },
        {
          jobNumber: "IC/567/8901_01_03",
          drawingNumber: "789012",
          workOrder: "7890",
          jobAttributes: [
            {
              width: 380,
              weight: 720,
              stack: null,
              packedWeight: null,
              scrap: null,
              excessWeight: null,
            },
            {
              width: 390,
              weight: 740,
              stack: null,
              packedWeight: null,
              scrap: null,
              excessWeight: null,
            },
            {
              width: 400,
              weight: 750,
              stack: null,
              packedWeight: null,
              scrap: null,
              excessWeight: null,
            },
            {
              width: 410,
              weight: 760,
              stack: null,
              packedWeight: null,
              scrap: null,
              excessWeight: null,
            },
          ],
        },
        {
          jobNumber: "IC/567/8901_01_04",
          drawingNumber: "890123",
          workOrder: "8901",
          jobAttributes: [
            {
              width: 370,
              weight: 700,
              stack: null,
              packedWeight: null,
              scrap: null,
              excessWeight: null,
            },
            {
              width: 380,
              weight: 710,
              stack: null,
              packedWeight: null,
              scrap: null,
              excessWeight: null,
            },
            {
              width: 390,
              weight: 720,
              stack: null,
              packedWeight: null,
              scrap: null,
              excessWeight: null,
            },
            {
              width: 400,
              weight: 730,
              stack: null,
              packedWeight: null,
              scrap: null,
              excessWeight: null,
            },
          ],
        },
        {
          jobNumber: "IC/567/8901_01_05",
          drawingNumber: "901234",
          workOrder: "9012",
          jobAttributes: [
            {
              width: 360,
              weight: 680,
              stack: null,
              packedWeight: null,
              scrap: null,
              excessWeight: null,
            },
            {
              width: 370,
              weight: 690,
              stack: null,
              packedWeight: null,
              scrap: null,
              excessWeight: null,
            },
            {
              width: 380,
              weight: 700,
              stack: null,
              packedWeight: null,
              scrap: null,
              excessWeight: null,
            },
            {
              width: 390,
              weight: 710,
              stack: null,
              packedWeight: null,
              scrap: null,
              excessWeight: null,
            },
          ],
        },
        {
          jobNumber: "IC/567/8901_01_01",
          drawingNumber: "123456",
          workOrder: "5678",
          jobAttributes: [
            {
              width: 400,
              weight: 800,
              stack: null,
              packedWeight: null,
              scrap: null,
              excessWeight: null,
            },
            {
              width: 420,
              weight: 850,
              stack: null,
              packedWeight: null,
              scrap: null,
              excessWeight: null,
            },
            {
              width: 410,
              weight: 820,
              stack: null,
              packedWeight: null,
              scrap: null,
              excessWeight: null,
            },
            {
              width: 430,
              weight: 870,
              stack: null,
              packedWeight: null,
              scrap: null,
              excessWeight: null,
            },
          ],
        },
        {
          jobNumber: "IC/567/8901_01_02",
          drawingNumber: "654321",
          workOrder: "6789",
          jobAttributes: [
            {
              width: 390,
              weight: 750,
              stack: null,
              packedWeight: null,
              scrap: null,
              excessWeight: null,
            },
            {
              width: 410,
              weight: 780,
              stack: null,
              packedWeight: null,
              scrap: null,
              excessWeight: null,
            },
            {
              width: 400,
              weight: 760,
              stack: null,
              packedWeight: null,
              scrap: null,
              excessWeight: null,
            },
            {
              width: 420,
              weight: 790,
              stack: null,
              packedWeight: null,
              scrap: null,
              excessWeight: null,
            },
          ],
        },
        {
          jobNumber: "IC/567/8901_01_03",
          drawingNumber: "789012",
          workOrder: "7890",
          jobAttributes: [
            {
              width: 380,
              weight: 720,
              stack: null,
              packedWeight: null,
              scrap: null,
              excessWeight: null,
            },
            {
              width: 390,
              weight: 740,
              stack: null,
              packedWeight: null,
              scrap: null,
              excessWeight: null,
            },
            {
              width: 400,
              weight: 750,
              stack: null,
              packedWeight: null,
              scrap: null,
              excessWeight: null,
            },
            {
              width: 410,
              weight: 760,
              stack: null,
              packedWeight: null,
              scrap: null,
              excessWeight: null,
            },
          ],
        },
        {
          jobNumber: "IC/567/8901_01_04",
          drawingNumber: "890123",
          workOrder: "8901",
          jobAttributes: [
            {
              width: 370,
              weight: 700,
              stack: null,
              packedWeight: null,
              scrap: null,
              excessWeight: null,
            },
            {
              width: 380,
              weight: 710,
              stack: null,
              packedWeight: null,
              scrap: null,
              excessWeight: null,
            },
            {
              width: 390,
              weight: 720,
              stack: null,
              packedWeight: null,
              scrap: null,
              excessWeight: null,
            },
            {
              width: 400,
              weight: 730,
              stack: null,
              packedWeight: null,
              scrap: null,
              excessWeight: null,
            },
          ],
        },
        {
          jobNumber: "IC/567/8901_01_05",
          drawingNumber: "901234",
          workOrder: "9012",
          jobAttributes: [
            {
              width: 360,
              weight: 680,
              stack: null,
              packedWeight: null,
              scrap: null,
              excessWeight: null,
            },
            {
              width: 370,
              weight: 690,
              stack: null,
              packedWeight: null,
              scrap: null,
              excessWeight: null,
            },
            {
              width: 380,
              weight: 700,
              stack: null,
              packedWeight: null,
              scrap: null,
              excessWeight: null,
            },
            {
              width: 390,
              weight: 710,
              stack: null,
              packedWeight: null,
              scrap: null,
              excessWeight: null,
            },
          ],
        },
      ],
      pagination: {
        current_page: 1,
        itemsPerPage: 30,
        total_Items: 5,
        total_pages: 1,
      },
    },
  };
};

export const ScanQr = () => {
  return {
    responseStatusList: {
      statusList: [
        {
          statusCode: 200,
          statusType: "success",
          statusDesc: "qrCodeNumber data fetched successfully",
        },
      ],
    },
    responseObject: {
      // data: {
      //   coilNumber: "IC/1A/1234",
      //   width: 1200,
      //   thickness: 0.27,
      //   coilGrade: "JR45E45EG",
      //   weight: 1200,
      //   supplierName: "Electrify2",
      //   materialType: "crgo",
      //   MTC1_5T: 11.23,
      //   MTC1_7T: 10.23,
      //   qrCodeNumber: "JIEGI45HEE454EGG",
      //   statusType: "ready",
      //   description: "This is for testing",

      //   rollsData: [
      //     {
      //       slittingProgramId: "SP12345",
      //       jobNumber: "NTPL/09/24/10434",
      //       drawingNumber: "MEHI-9089(C-4725)(A)",
      //       workOrderNumber: "WO/11/09/11168",
      //       rollNumber: "IC/1A/1234_01",
      //       stacks: 10,
      //       width: 240,
      //       thickness: 0.27,
      //       length: 2000,
      //       weight: 209.05,
      //       cuttInMeters: 1000,
      //       rollStatus: "hold",
      //       subStatus: {
      //         statusType: "aesthetic",
      //         substatusType: "black and white marks",
      //       },
      //       statusDescription: "other reason for holding",
      //       qrCodeNumber: "QR123456789",
      //       productionLine: "PL01",
      //       actualWeight: 1480,
      //       scrapType: "startRoll",
      //       createdBy: "supervisor",
      //       updatedBy: null,
      //       createdAt: "2025-01-01T17:03:20.000Z",
      //       updatedAt: "2025-01-01T17:03:20.000Z",
      //     },
      //     {
      //       slittingProgramId: "SP1245345",
      //       jobNumber: "NTPL/09/24/10434",
      //       drawingNumber: "MEHI-9089(C-4725)(A)",
      //       workOrderNumber: "WO/11/09/11168",
      //       rollNumber: "IC/1A/1234_02",
      //       stacks: 10,
      //       width: 230,
      //       thickness: 0.27,
      //       length: 2000,
      //       weight: 198.15,
      //       cuttInMeters: 1000,
      //       rollStatus: "ready",
      //       subStatus: null,
      //       statusDescription: "other reason for holding",
      //       qrCodeNumber: "QR14523456789",
      //       productionLine: "PL01",
      //       actualWeight: 1480,
      //       scrapType: "endRoll",
      //       createdBy: "supervisor",
      //       updatedBy: "operator",
      //       createdAt: "2025-01-01T17:03:20.000Z",
      //       updatedAt: "2025-01-01T17:03:20.000Z",
      //     },
      //     {
      //       slittingProgramId: "SP12345",
      //       jobNumber: "NTPL/09/24/10434",
      //       drawingNumber: "MEHI-9089(C-4725)(A)",
      //       workOrderNumber: "WO/11/09/11168",
      //       rollNumber: "IC/1A/1234_03",
      //       stacks: 10,
      //       width: 220,
      //       thickness: 0.27,
      //       length: 2000,
      //       weight: 189.05,
      //       cuttInMeters: 1000,
      //       rollStatus: "ready",
      //       subStatus: {
      //         statusType: "aesthetic",
      //         substatusType: "black and white marks",
      //       },
      //       statusDescription: "other reason for holding",
      //       qrCodeNumber: "QR123456789",
      //       productionLine: "PL01",
      //       actualWeight: 1480,
      //       scrapType: "startRoll",
      //       createdBy: "supervisor",
      //       updatedBy: null,
      //       createdAt: "2025-01-01T17:03:20.000Z",
      //       updatedAt: "2025-01-01T17:03:20.000Z",
      //     },
      //     {
      //       slittingProgramId: "SP1245345",
      //       jobNumber: "NTPL/09/24/10434",
      //       drawingNumber: "MEHI-9089(C-4725)(A)",
      //       workOrderNumber: "WO/11/09/11168",
      //       rollNumber: "IC/1A/1234_04",
      //       stacks: 10,
      //       width: 210,
      //       thickness: 0.27,
      //       length: 2000,
      //       weight: 152.34,
      //       cuttInMeters: 1000,
      //       rollStatus: "block",
      //       subStatus: null,
      //       statusDescription: "other reason for holding",
      //       qrCodeNumber: "QR14523456789",
      //       productionLine: "PL01",
      //       actualWeight: 1480,
      //       scrapType: "endRoll",
      //       createdBy: "supervisor",
      //       updatedBy: "operator",
      //       createdAt: "2025-01-01T17:03:20.000Z",
      //       updatedAt: "2025-01-01T17:03:20.000Z",
      //     },
      //   ],
      //   documentID: ["da39d7b7-4e44-42e2-b8a2-dbeafd150324"],
      //   registeredDate: "2024-12-27",
      //   createdAt: "2025-01-01T17:03:20.000Z",
      //   updatedAt: "2025-01-01T17:03:20.000Z",
      //   endDate: null,
      // },
      data: {
        coilNumber: "IC/24/2000",
        width: 43,
        thickness: 0.24,
        grade: "25090",
        weight: 300,
        supplierName: null,
        materialType: null,
        MTC1_5T: 2200,
        MTC1_7T: 2400,
        qrCodeNumber: "feed7b3d-e91c-41c5-b0bd-f5af4001f482",
        statusType: "fullyUtilize",
        description: null,
        documentID: [],
        registeredDate: "2025-01-23",
        createdAt: "2025-01-21T15:41:38.000Z",
        updatedAt: "2025-01-21T10:14:22.397Z",
        endDate: null,
        slittingDetail: [
          {
            slittingProgramId: "f44e43f8-8070-4f54-bc61-2e7c5c7a9fc6",
            slittingProgramStatus: "none",
            coilNumber: "IC/24/2000",
            weight: 300,
            thickness: 0.24,
            width: 43,
            documentId: [],
            programStatus: "Slitting_Start",
            statusDescription: null,
            createdAt: "2025-01-21T15:44:22.000Z",
            updatedAt: "2025-01-21T15:44:22.000Z",
            createdBy: "Slitting Supervisor",
            updatedBy: null,
            endDate: null,
            rollsData: [
              {
                rollId: "524c8ddb-0e7e-4730-80f9-3f5e5a484786",
                rollNumber: "IC/24/2000-ff472f73",
                jobId: null,
                jobNumber: "122",
                drawingNumber: "123",
                workOrder: "24",
                stack: 3,
                width: 2,
                thickness: 0.24,
                length: 3,
                weight: 0.07364,
                splittingId: null,
                programStatus: "Slitting_Start",
                rollStatus: "ready",
                subStatus: {},
                actualWeight: null,
                scrapType: null,
                productionLine: null,
                updatedFor: null,
                createdAt: "2025-01-21T15:44:22.000Z",
                updatedAt: "2025-01-21T15:44:22.000Z",
                createdBy: "Slitting Supervisor",
                updatedBy: null,
                endDate: null,
                slittingProgramId: "f44e43f8-8070-4f54-bc61-2e7c5c7a9fc6",
              },
              {
                rollId: "104e9d73-b68e-40ba-bce5-ef178d1a7f59",
                rollNumber: "Extra-93aba187",
                jobId: "5a5bc9db-1255-457e-b80c-a9e49c696230",
                jobNumber: null,
                drawingNumber: null,
                workOrder: null,
                stack: 3,
                width: 41,
                thickness: 0.24,
                length: null,
                weight: 299.93,
                splittingId: null,
                programStatus: "Slitting_Start",
                rollStatus: "extra",
                subStatus: {},
                actualWeight: null,
                scrapType: null,
                productionLine: null,
                updatedFor: null,
                createdAt: "2025-01-21T15:44:22.000Z",
                updatedAt: "2025-01-21T15:44:22.000Z",
                createdBy: "Slitting Supervisor",
                updatedBy: null,
                endDate: null,
                slittingProgramId: "f44e43f8-8070-4f54-bc61-2e7c5c7a9fc6",
              },
            ],
          },
        ],
        document: [],
      },
    },
  };
};
